### ISSUE TITLE
RollTables not showing in roll channel till leaving and coming back

### ISSUE THREAD

**Issue by sharkbruhaha** [cswendrowski/FoundryVTT-Tabbed-Chatlog#25]
Whenever dice roll, they show up immidiately, but when rollTables roll they are not shown in the roll chat till you leave the tab for OOC/ic and back, even to other element tabs doesn't proc an update. Meanwhile dice rolls will keep showing up.

**Comment by RicoTheBold** [comment]
Happening for me, too.  It also occurs if the visibility changes on the card in the chatlog, so a pretty common scenario for me right now is:

- Use a rolltable to get a "card draw" result, but dang it, I can't see it in the chatlog
- Okay, click on OOC and then back to Rolls
- Oh, of course, I'm rolling in Private GM Roll, so I right-click the entry and Reveal to Everyone . . . and it's gone
- Click back on OOC and back to Rolls and there it is again

Super annoying.  It didn't used to do this, but I'm not sure when exactly it broke - might've been Foundry 0.7x, but it's doing it for me in Foundry VTT 0.7.7 and Tabbed Chatlog 1.5.7 right now.  It's been at least a few weeks, though.

**Comment by jenthura** [comment]
Happens for me too.

**Comment by cswendrowski** [comment]
Thanks for the report, will investigate a fix

**Comment by Djahal** [comment]
Hello !
Just wanna say it is still happening and now it also freezes the chatlog sometimes. Had to desactivate the module :/.
Thanks for the work though :).

→ Foundry 0.7.9.

**Comment by Tyaeth** [comment]
Not sure if this was other peoples experience, but using "Find the Culprit" this only seemed to happen to me while the "Dice so Nice!" module is active.

**Comment by cswendrowski** [comment]
Fixed in v1.6.0

**Comment by Tyaeth** [comment]
I'm still experiencing this issue when Dice So Nice is active. The only modules I have activated to test are:
- Dice So Nice v3.3.2
- Tabbed Chatlog v1.6.0
- Find the culprit v1.1.3

**Comment by cswendrowski** [comment]
Hey there @Tyaeth - I cannot currently reproduce. It's possible you grabbed one of the autobuilt versions of 1.6.0 - I haven't released the final one yet. I'll be releasing it momentarily - could you reverify, and if it still occurs, let me know what System you're playing in?

**Comment by Tyaeth** [comment]
That was the issue - I saw 1.6.0 on github and jumped the gun. It works great now, thanks for the fix!

**Comment by RicoTheBold** [comment]
I thought it was still happening to me, but it turns out that the 1.6.0 manifest points at the 1.5.8 .zip file, so my module wasn't updating properly.  Confirmed fixed for me with Dice So Nice and PF2 as the system as well, and can also confirm that with 1.5.8 I was able to reproduce with just those two modules, with 1.6.0 it seems fixed.  Opened a new issue for the manifest problem.
